# Generated by Django 3.1 on 2020-08-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stonk',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('halal_status', models.CharField(choices=[('Y', 'Halal'), ('N', 'Not halal'), ('Q', 'Questionable')], default='N', max_length=2)),
                ('annual_dividend', models.FloatField()),
                ('dividend_per_dollar', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
