# Generated by Django 3.1 on 2020-08-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20200830_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='stonk',
            name='name',
            field=models.CharField(default='TO BE BACKFILLED', max_length=200),
            preserve_default=False,
        ),
    ]
